### ISSUE TITLE
Version 3.0.2 is broken on Clojure 1.9 with spec instrumentation

### ISSUE THREAD

**Issue by peter** [michaelklishin/monger#142] opened 2016-08-21 20:44 UTC
The offending line is this defn in core.clj:

(defn ^MongoClientOptions$Builder mongo-options-builder
  [{:keys [connections-per-host threads-allowed-to-block-for-connection-multiplier
           max-wait-time connect-timeout socket-timeout socket-keep-alive auto-connect-retry max-auto-connect-retry-time
           description write-concern cursor-finalizer-enabled read-preference
           required-replica-set-name] :or [auto-connect-retry true]}]
...

If you change the :or clause to be a map rather than a vector it works fine:

(defn ^MongoClientOptions$Builder mongo-options-builder
  [{:keys [connections-per-host threads-allowed-to-block-for-connection-multiplier
           max-wait-time connect-timeout socket-timeout socket-keep-alive auto-connect-retry max-auto-connect-retry-time
           description write-concern cursor-finalizer-enabled read-preference
           required-replica-set-name] :or {auto-connect-retry true}}]

Any chance a fix like this would go out soon for a 3.0.3 release? I noticed this is also fixed on master since this code is no longer there. Should I be using monger as a git dependency maybe until 3.1 is out? I'm in a development phase at the moment and expect to be in production in a couple of months.

Thanks!

**Comment by michaelklishin** [comment] 2016-08-22 06:38
Duplicate of https://github.com/michaelklishin/monger/issues/137.

**Closed by michaelklishin** 2016-08-22 06:38 UTC
